import { UserProvider } from "@/lib/user-context"; // ADD THIS
import { AppLayout } from "@/components/layout/AppLayout";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TrevorAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased bg-gray-100 vsc-initialized`}>
        <UserProvider> {/* <-- WRAP EVERYTHING */}
          <AppLayout>{children}</AppLayout>
        </UserProvider>
      </body>
    </html>
  );
}
